export {default as Navbar} from './Navbar'
export {default as Cryptocurrencies} from './CryptoCurrencies'
export {default as CryptoDetails} from './Cryptodetails'
export {default as Homepage} from './Homepage'
export {default as News} from './News'
